const brtRoutes = [
  {
    id: "1",
    number: "1",
    route_name: "Blok M - Kota",
    direction: "Blok M → Kota",
    stops: [
      "Blok M",
      "ASEAN",
      "Kejaksaan Agung",
      "Masjid Agung",
      "Bundaran Senayan",
      "Senayan Bank DKI",
      "Polda Metro Jaya",
      "Bendungan Hilir",
      "Karet",
      "Dukuh Atas",
      "Tosari",
      "Bundaran HI ASTRA",
      "M.H. Thamrin",
      "Kebon Sirih",
      "Monumen Nasional",
      "Harmoni",
      "Sawah Besar",
      "Mangga Besar",
      "Taman Sari",
      "Glodok",
      "Kota",
      "Museum Sejarah Jakarta",
      "Kali Besar",
    ],
  },
  {
    id: "1A",
    number: "1A",
    route_name: "Pantai Maju - Balai Kota",
    direction: "Pantai Maju → Balai Kota",
    stops: [
      "Pantai Maju",
      "The Violin",
      "Melody Golf 2",
      "Seberang Food Street",
      "The Piano",
      "Fresh Market PIK",
      "PIK Avenue",
      "Ruko Cordoba 1",
      "Waterbom Jakarta 1",
      "RS PIK",
      "Mandara Permai 6",
      "Mediterania Boulevard",
      "Galeri Niaga Mediterania 2",
      "SMAK Penabur Enam 1",
      "Muara Angke",
      "Baywalk 2",
      "SD Diakonia 1",
      "Stella Maris 1",
      "Waduk Pluit",
      "Pluit Sakti",
      "Pluit Selatan",
      "Pakin",
      "Gedong Panjang",
      "Museum Sejarah Jakarta",
      "Kota",
      "Glodok",
      "Taman Sari",
      "Mangga Besar",
      "Sawah Besar",
      "Harmoni",
      "Monumen Nasional",
      "Balai Kota",
    ],
  },
  {
    id: "1B",
    number: "1B",
    route_name: "Stasiun Palmerah - Transport Hub Dukuh Atas",
    direction: "Stasiun Palmerah → Transport Hub Dukuh Atas",
    stops: [
      "Stasiun Palmerah",
      "Graha Kemenpora",
      "TVRI",
      "Taman Ria",
      "Senayan Arah Timur",
      "Benhil 2",
      "MRT Bendungan Hilir 3 – Sudirman Suites",
      "Karet",
      "Dukuh Atas",
      "Tosari",
      "Transport Hub Dukuh Atas",
    ],
  },
  {
    id: "1C",
    number: "1C",
    route_name: "Pesanggrahan - Blok M",
    direction: "Pesanggrahan → Blok M",
    stops: [
      "Pesanggrahan",
      "Pondok Indah 2",
      "Pondok Indah 1",
      "Taman Puring",
      "Kebayoran Lama Velbak 1",
      "Jalan Bulungan 1",
      "RS Pusat Pertamina 1",
      "Mayestik 1",
      "CSW 2",
      "Jalan Palatehan",
      "Blok M",
    ],
  },
  {
    id: "1E",
    number: "1E",
    route_name: "Pondok Labu - Blok M",
    direction: "Pondok Labu → Blok M",
    stops: [
      "Taman DDN",
      "SMPN 85",
      "Pasar Pondok Labu",
      "Jalan H. Ipin",
      "Jalan H. Muslim",
      "One Belpark 2",
      "Dapsus 2",
      "Kantor Pos Fatmawati",
      "Jalan Banjarsari II",
      "Pasar Mede",
      "SMKN 28",
      "RS Setia Mitra 2",
      "Cipete Raya 2",
      "Golden Fatmawati",
      "Jalan Mangga",
      "H. Nawi / Madrasah",
      "Seberang ITC Fatmawati",
      "Jalan Gotong Royong",
      "Blok A Petogogan",
      "Jalan Sungai Sambas VI",
      "Plaza Blok M",
      "Kwitang 6 PSKD",
      "Jalan Bulungan 2",
      "Blok M Jalur 3",
    ],
  },
  {
    id: "1F",
    number: "1F",
    route_name: "Stasiun Palmerah - Bundaran Senayan",
    direction: "Stasiun Palmerah → Bundaran Senayan",
    stops: [
      "Stasiun Palmerah",
      "Graha Kemenpora",
      "TVRI",
      "Taman Ria",
      "Senayan Arah Timur",
      "Gelora Bung Karno",
      "Bundaran Senayan",
    ],
  },
  {
    id: "1H",
    number: "1H",
    route_name: "Stasiun Tanah Abang - Stasiun Gondangdia",
    direction: "Stasiun Tanah Abang → Stasiun Gondangdia",
    stops: [
      "St. Gondangdia 2",
      "Masjid Cut Nyak Dien",
      "Khong Guan Wahid Hasyim",
      "Seberang the Pakubuwono Menteng",
      "MH Thamrin 3",
      "Seberang Jalan Kampung Bali XXXIII",
      "Jalan Kebon Kacang X",
      "Jalan Kebon Kacang VIII",
      "Simpang Blok A",
      "Tanah Abang AURI",
      "Blok E",
      "Pharmin",
      "Explorer Tanah Abang",
      "Blok F",
      "Pospol Jati Bunder",
      "JPO Blok G",
      "Jak Lingko Tanah Abang 2",
    ],
  },
  {
    id: "1M",
    number: "1M",
    route_name: "Meruya TAMAN Aries - Blok M",
    direction: "Meruya TAMAN Aries → Blok M",
    stops: [
      "Meruya TAMAN Aries",
      "Ruko Aries Niaga",
      "Pospol TAMAN Aries",
      "Seberang Masjid Nurul Iman Kubur Batu",
      "Aries Utama III",
      "Olieku Jalan Aries Permai",
      "Aries Utama",
      "Seberang SPBU Meruya Ilir",
      "Simpang Meruya Ilir 1",
      "Blok M",
    ],
  },
  {
    id: "1N",
    number: "1N",
    route_name: "Tanah Abang - Blok M",
    direction: "Tanah Abang → Blok M",
    stops: [
      "Jak Lingko Tanah Abang 2",
      "JPO Blok G",
      "Pospol Jati Bunder",
      "Blok F",
      "Explorer Tanah Abang",
      "Pharmin",
      "Blok E",
      "Tanah Abang AURI",
      "Simpang Blok A",
      "Jalan Kebon Kacang VIII",
      "Jalan Kebon Kacang X",
      "Seberang Jalan Kampung Bali XXXIII",
      "MH Thamrin 3",
      "Seberang the Pakubuwono Menteng",
      "Khong Guan Wahid Hasyim",
      "Masjid Cut Nyak Dien",
      "St. Gondangdia 2",
    ],
  },
  {
    id: "1P",
    number: "1P",
    route_name: "Senen - Blok M",
    direction: "Terminal Senen → Blok M",
    stops: [
      "Terminal Senen",
      "Kelurahan Senen",
      "Bangau VI",
      "Simpang Gunung Sahari III",
      "Sekolah Penabur Gunung Sahari",
      "Pasar Senen Jaya",
      "Atrium 1",
      "RSPAD 1",
      "RSPAD 2",
      "Museum Kebangkitan",
      "Gunung Agung",
      "Telkom Grapari",
      "Balai Kota 1",
      "Perpustakaan Nasional",
      "Dana Reksa",
      "Wisma Mandiri",
      "Sari Pan Pacific",
      "MH Thamrin 1",
      "Wisma Nusantara",
      "Tosari 1",
      "Tosari 3",
      "Dukuh Atas 3",
      "Bumiputera",
      "Chase Plaza",
      "Karet Sudirman 1",
      "Flyover Karet 2",
      "Plaza Sentral",
      "Blok M",
    ],
  },
  {
    id: "1Q",
    number: "1Q",
    route_name: "Situ Gintung 2 - Blok M",
    direction: "Situ Gintung 2 → Blok M",
    stops: [
      "Situ Gintung 2",
      "Situ Gintung 3",
      "SD Rempoa 4",
      "Jalan Pesona Gintung",
      "Perum Griya Bumiputera",
      "Jl Garuda",
      "Masjid Jami AL Jihad",
      "Masjid Jami’ Tajriyah",
      "ACE Hardware Rempoa",
      "Giant Express Rempoa",
      "Blok M",
    ],
  },
  {
    id: "1W",
    number: "1W",
    route_name: "Blok M - Ancol",
    direction: "Blok M → Ancol",
    stops: [
      "Blok M Jalur 5",
      "ASEAN",
      "Kejaksaan Agung",
      "Masjid Agung",
      "Bundaran Senayan",
      "Senayan Bank DKI",
      "Gerbang Pemuda",
      "Petamburan",
      "Kemanggisan",
      "JIExpo Kemayoran",
      "Ancol",
    ],
  },
  {
    id: "2",
    number: "2",
    route_name: "Pulo Gadung - Monumen Nasional",
    direction: "Pulo Gadung → Monumen Nasional",
    stops: [
      "Pulo Gadung 1",
      "Pulo Gadung 2",
      "Pemuda Rawamangun",
      "Velodrome",
      "Utan Kayu",
      "Pramuka BPKP",
      "Pramuka LIA",
      "Matraman",
      "Tegalan",
      "Senen",
      "Atrium Senen",
      "Kwitang",
      "Gambir 1",
      "Monumen Nasional",
    ],
  },
  {
    id: "2A",
    number: "2A",
    route_name: "Pulo Gadung - Rawa Buaya (via Balai Kota)",
    direction: "Pulo Gadung → Rawa Buaya",
    stops: [
      "Pulo Gadung",
      "Bermis",
      "Pulo Mas",
      "Perintis Kemerdekaan",
      "Pedongkelan",
      "Cempaka Mas",
      "Sumur Batu",
      "Cempaka Baru",
      "Pasar Cempaka Putih",
      "Rawa Selatan",
      "Galur",
      "Pasar Senen",
      "Kwitang",
      "Balai Kota",
      "Petojo",
      "Roxy",
      "Grogol",
      "Jelambar",
      "Damai",
      "Taman Kota",
      "Jembatan Gantung",
      "Pulo Nangka",
      "Jembatan Baru",
      "Rawa Buaya",
    ],
  },
  {
    id: "2B",
    number: "2B",
    route_name: "Pulo Gadung - Harapan Indah",
    direction: "Pulo Gadung → Harapan Indah",
    stops: [
      "Pulo Gadung",
      "Warung Jengkol",
      "Jalan Kesadaran Pool Bus 1",
      "Jalan Kesadaran Pool Bus 2",
      "Sbr. PTC Pulo Gadung",
      "Sbr. IGI",
      "Jln. Gg. Swadaya IV",
      "Tipar Cakung 1",
      "Cakung United Tractor Selatan",
      "Pasar Cakung 1",
      "… (halte tengah hingga) …",
      "Harapan Indah",
    ],
  },
  {
    id: "2F",
    number: "2F",
    route_name: "Pulo Gadung - Rusun Cakung Barat (Albo)",
    direction: "Pulo Gadung → Rusun Cakung Barat",
    stops: [
      "Pulo Gadung",
      "Warung Jengkol",
      "Makam Wakaf",
      "Jalan Kesadaran Pool Bus",
      "PTC Pulo Gadung",
      "IGI",
      "Gang Swadaya 4",
      "Tipar Cakung",
      "Cakung United Tractors",
      "SMK Nurul Huda",
      "Penggilingan / Raya Penggilingan",
      "Pasar Cakung",
      "Musholla Nurul Islam Tipar Cakung",
      "Komplek Rusun Griya Tipar Cakung",
      "Rusun Cakung Barat / Albo",
    ],
  },
  {
    id: "2H",
    number: "2H",
    route_name: "Rusun Jati Rawasari - Senen",
    direction: "Rusun Jati Rawasari → Senen",
    stops: [
      "Rusun Jati Rawasari",
      "SDN Johar Baru 10",
      "Seberang Pasar Gembrong Baru",
      "Sbr. Gg. Adjid",
      "Jalan Galur Jaya",
      "Bengkel Jalan Letjen Suprapto",
      "Honda Letjen Suprapto",
      "RSPAD 1",
    ],
  },
  {
    id: "2P",
    number: "2P",
    route_name: "Senen - Transport Hub Dukuh Atas",
    direction: "Senen → Transport Hub Dukuh Atas",
    stops: [
      "Terminal Senen",
      "Kelurahan Senen",
      "Bangau VI",
      "Simpang Gunung Sahari III",
      "Sekolah Penabur Gunung Sahari",
      "Pasar Senen Jaya",
      "Atrium 1",
      "RSPAD 1 / RSPAD",
      "Museum Kebangkitan / Museum Kebangkitan Nasional",
      "Gunung Agung",
      "Telkom GraPARI",
      "Balai Kota 1",
      "Perpustakaan Nasional",
      "Dana Reksa",
      "Wisma Mandiri",
      "Sari Pan Pacific",
      "MH Thamrin 1",
      "Wisma Nusantara",
      "Tosari 1",
      "Tosari 3",
      "Dukuh Atas 3",
      "Bumiputera",
      "Chase Plaza",
      "Karet Sudirman 1",
      "Flyover Karet 2",
      "Plaza Sentral",
      "Transport Hub Dukuh Atas",
    ],
  },
  {
    id: "2Q",
    number: "2Q",
    route_name:
      "Selatan Stasiun Gondangdia - Balai Kota / Perpustakaan Nasional",
    direction:
      "Selatan Stasiun Gondangdia → Perpustakaan Nasional / Balai Kota",
    stops: [
      "Selatan Stasiun Gondangdia",
      "Masjid Cut Meutia 1",
      "BRI Menteng",
      "Kanisius",
      "Telkom GraPARI",
      "Perpustakaan Nasional",
      "Balai Kota",
    ],
  },
  {
    id: "3",
    number: "3",
    route_name: "Kalideres - Monumen Nasional",
    direction: "Kalideres → Monumen Nasional",
    stops: [
      "Kalideres",
      "Jembatan Baru",
      "Rawa Buaya",
      "Sumur Bor",
      "Pulo Nangka",
      "Jembatan Gantung",
      "Taman Kota",
      "Jelambar",
      "Grogol",
      "Roxy",
      "Petojo",
      "Pejambon",
      "Juanda",
      "Monumen Nasional",
    ],
  },
  {
    id: "3A",
    number: "3A",
    route_name: "Rusun Pesakih - Kalideres",
    direction: "Rusun Pesakih → Kalideres",
    stops: [
      "Rusun Pesakih",
      "Masjid Raya KH. Hasyim Asyari",
      "Jembatan Pesakih Semanan",
      "Pesakih 2",
      "Kalideres 1",
    ],
  },
  {
    id: "3B",
    number: "3B",
    route_name: "Kalideres - Puri Beta / Duri",
    direction: "Kalideres → Puri Beta / Duri",
    stops: [
      "Kalideres",
      "Jembatan Baru",
      "Rawa Buaya",
      "Sumur Bor",
      "Pulo Nangka",
      "Jembatan Gantung",
      "Taman Kota",
      "Kebon Jeruk",
      "Puri Beta",
      "Duri",
    ],
  },
  {
    id: "3C",
    number: "3C",
    route_name: "Rusun Kapuk Muara - Penjaringan",
    direction: "Rusun Kapuk Muara → Penjaringan",
    stops: [
      "Rusun Kapuk Muara",
      "Kapuk Muara",
      "Pluit Utara",
      "Jembatan Tiga",
      "Muara Karang",
      "Pluit",
      "Penjaringan",
    ],
  },
  {
    id: "3D",
    number: "3D",
    route_name: "Cengkareng - Pasar Baru",
    direction: "Cengkareng → Pasar Baru",
    stops: [
      "Cengkareng",
      "Kembangan",
      "Puri Indah",
      "Taman Kota",
      "Slipi",
      "Tomang",
      "Grogol",
      "Duri",
      "Pasar Baru",
    ],
  },
  {
    id: "3E",
    number: "3E",
    route_name: "Kalideres - Harmoni",
    direction: "Kalideres → Harmoni",
    stops: [
      "Kalideres",
      "Jembatan Baru",
      "Rawa Buaya",
      "Sumur Bor",
      "Pulo Nangka",
      "Jembatan Gantung",
      "Taman Kota",
      "Jelambar",
      "Grogol",
      "Roxy",
      "Petojo",
      "Pejambon",
      "Juanda",
      "Kota",
      "Harmoni",
    ],
  },
  {
    id: "3F",
    number: "3F",
    route_name: "Kalideres - Senayan Bank DKI",
    direction: "Kalideres → Senayan Bank DKI",
    stops: [
      "Kalideres",
      "Jembatan Baru",
      "Rawa Buaya",
      "Sumur Bor",
      "Pulo Nangka",
      "Jembatan Gantung",
      "Taman Kota",
      "Jelambar",
      "Grogol",
      "Roxy",
      "Slipi",
      "Tomang",
      "Grogol (via Jalan S. Parman)",
      "Gelora Bung Karno",
      "Senayan Bank DKI",
    ],
  },
  {
    id: "3H",
    number: "3H",
    route_name: "Pesakih - Juanda",
    direction: "Pesakih → Juanda",
    stops: [
      "Pesakih",
      "Masjid Raya KH Hasyim Asy’ari",
      "Jembatan Pesakih Semanan",
      "Sumur Bor",
      "Pulo Nangka",
      "Jembatan Gantung",
      "Taman Kota",
      "Jelambar",
      "Grogol",
      "Roxy",
      "Lev / Mangga Besar",
      "Juanda",
    ],
  },
  // Koridor 4 dan variannya (contoh objek)

  {
    id: "4",
    number: "4",
    route_name: "Pulo Gadung 2 - Dukuh Atas 2 (Galunggung)",
    direction: "Pulo Gadung 2 → Galunggung / Dukuh Atas 2",
    stops: [
      "Pulo Gadung 2",
      "Pasar Pulo Gadung",
      "TU Gas",
      "Layur",
      "Pemuda Rawamangun",
      "Velodrome",
      "Kayu Jati",
      "Rawamangun",
      "Simpang Pramuka",
      "Pramuka Sari",
      "Utan Kayu",
      "Pasar Genjing",
      "Flyover Pramuka",
      "Manggarai",
      "Pasar Rumput",
      "Halimun 3",
      "Galunggung",
    ],
  },
  {
    id: "4B",
    number: "4B",
    route_name: "Universitas Indonesia - Stasiun Manggarai",
    direction: "UI → Stasiun Manggarai",
    stops: [
      "Universitas Indonesia",
      "Depok / UI gate",
      "Sudirman",
      "Kampung Melayu",
      "Manggarai",
    ],
  },
  {
    id: "4C",
    number: "4C",
    route_name: "TU Gas 2 - Bundaran Senayan",
    direction: "TU Gas 2 → Bundaran Senayan 2",
    stops: [
      "TU Gas 2",
      "FX Sudirman",
      "GBK Pintu 7",
      "Benhil 2",
      "MRT Bendungan Hilir 3  Sudirman Suites",
      "Karet Sudirman 2",
      "Karet Sudirman 3",
      "Grand Sahid",
      "Menara Astra",
      "Dukuh Atas 4",
      "Tosari 3  Blora",
      "Tosari 1",
      "Grah Mandiri",
      "KPU",
      "Museum Proklamasi",
      "Gedung Wanita",
      "SMPN 8",
      "Jl. Penataran",
      "Tugu Proklamasi 2",
      "Tugu Proklamasi",
      "Simpang Matraman 2",
      "Jl. Pramuka 2",
      "Pasar Pramuka",
      "Jl. Pramuka 1",
      "Jl. Pramuka 4",
      "Pramuka LIA 2",
      "BPKP 2",
      "UNJ 2",
      "Sunan Giri 2",
      "Velodrome 1",
      "Arion Mall",
      "Jl. Sunan Drajad",
      "Layur 1",
      "TU Gas 2",
    ],
  },
  {
    id: "4D",
    number: "4D",
    route_name: "Pulo Gadung - Kuningan",
    direction: "Pulo Gadung → Kuningan",
    stops: [
      "Pulo Gadung",
      "Pasar Pulo Gadung",
      "TU Gas",
      "Layur",
      "Pemuda Rawamangun",
      "Velodrome",
      "Sudirman",
      "Kuningan",
    ],
  },
  {
    id: "4E",
    number: "4E",
    route_name: "Rusun Jatinegara Kaum - Pulo Gadung",
    direction: "Rusun Jatinegara Kaum → Pulo Gadung",
    stops: ["Rusun Jatinegara Kaum", "Jatinegara", "Pulo Gadung"],
  },
  {
    id: "4F",
    number: "4F",
    route_name: "Pulo Gadung - Pinang Ranti",
    direction: "Pulo Gadung → Pinang Ranti",
    stops: [
      "Pulo Gadung",
      "Pasar Pulo Gadung",
      "TU Gas",
      "… (halte tengah di Rawamangun, Jatinegara) …",
      "Pinang Ranti",
    ],
  },
  {
    id: "4K",
    number: "4K",
    route_name: "Pulo Gadung - Kejaksaan Agung",
    direction: "Pulo Gadung → Kejaksaan Agung",
    stops: ["Pulo Gadung", "CSW", "Kejaksaan Agung"],
  },
  {
    id: "5",
    number: "5",
    route_name: "Kampung Melayu - Ancol",
    direction: "Kampung Melayu → Ancol",
    stops: [
      "Kampung Melayu",
      "Jatinegara",
      "Bali Mester",
      "Matraman Baru",
      "Kesatrian",
      "Tegalan",
      "Matraman",
      "Paseban",
      "Salemba",
      "Kramat Sentiong",
      "PAL Putih",
      "Senen Sentral",
      "Lapangan Banteng",
      "Pasar Baru Timur",
      "Jembatan Merah",
      "Gunung Sahari",
      "Pademangan",
      "Ancol",
    ],
  },

  {
    id: "6",
    number: "6",
    route_name: "Ragunan - Galunggung",
    direction: "Ragunan → Galunggung",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Taman Margasatwa",
      "H. R. Rasuna Said",
      "Kendal",
      "Laturharhary",
      "Sultan Agung",
      "Setiabudi Barat",
      "Setiabudi Tengah",
      "Galunggung",
    ],
  },
  {
    id: "6A",
    number: "6A",
    route_name: "Ragunan - Balai Kota via Kuningan",
    direction: "Ragunan → Balai Kota",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Underpass Kuningan",
      "Patra Kuningan",
      "Karet",
      "Karet Sudirman",
      "Setiabudi Barat",
      "Setiabudi Tengah",
      "Dukuh Atas",
      "Sudirman",
      "Balai Kota",
    ],
  },
  {
    id: "6B",
    number: "6B",
    route_name: "Ragunan - Balai Kota via Semanggi",
    direction: "Ragunan → Balai Kota",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Semanggi",
      "Sudirman",
      "Balai Kota",
    ],
  },
  {
    id: "6C",
    number: "6C",
    route_name: "Stasiun Tebet - Kuningan",
    direction: "Stasiun Tebet → Kuningan",
    stops: [
      "Stasiun Tebet 2 - Pintu Barat",
      "Departemen Kesehatan",
      "Karet",
      "Karet Sudirman",
      "Setiabudi Barat",
      "Setiabudi Tengah",
      "Kuningan",
    ],
  },
  {
    id: "6D",
    number: "6D",
    route_name: "Stasiun Tebet - Bundaran Senayan",
    direction: "Stasiun Tebet → Bundaran Senayan",
    stops: [
      "Stasiun Tebet 2 - Pintu Barat",
      "Departemen Kesehatan",
      "Mampang Prapatan",
      "Semanggi",
      "Sudirman",
      "Bundaran Senayan",
    ],
  },
  {
    id: "6H",
    number: "6H",
    route_name: "Senen - Lebak Bulus",
    direction: "Senen → Lebak Bulus",
    stops: [
      "Senen Sentral",
      "Wahidin 2",
      "TAMAN Wahidin",
      "SMA Budi Utomo",
      "Kantor Pos Lapangan Banteng",
      "Lapangan Banteng 1",
      "Pejambon",
      "Seberang Stasiun Gambir",
      "Galeri Nasional",
      "Tugu Tani 1",
      "Tugu Tani 2",
      "Simpang Kanisius",
      "Kantor Pos Cikini",
      "TAMAN Ismail Marzuki",
      "ABA",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
    ],
  },
  {
    id: "6K",
    number: "6K",
    route_name: "Kuningan - Karet",
    direction: "Kuningan → Karet",
    stops: [
      "Kuningan",
      "Patra Kuningan",
      "Underpass Kuningan",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Karet",
    ],
  },
  {
    id: "6M",
    number: "6M",
    route_name: "Stasiun Manggarai - Blok M",
    direction: "Stasiun Manggarai → Blok M",
    stops: [
      "Stasiun Manggarai Timur",
      "Kampung Melayu",
      "Kampung Rambutan",
      "Pasar Rebo",
      "Cipinang",
      "Jatinegara",
      "Matraman",
      "Tegalan",
      "Senen",
      "Atrium Senen",
      "Kwitang",
      "Gambir 1",
      "Monumen Nasional",
      "Bundaran HI",
      "Sudirman",
      "Blok M",
    ],
  },
  {
    id: "6N",
    number: "6N",
    route_name: "Ragunan - Blok M via Kemang",
    direction: "Ragunan → Blok M",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Kemang",
      "Mampang Prapatan",
      "Jati Padang",
      "Jati Barat",
      "Simpang Ragunan Ar-Raudhah",
      "Ragunan",
    ],
  },
  {
    id: "6P",
    number: "6P",
    route_name: "Pasar Minggu - Velbak via Kebon Jeruk",
    direction: "Pasar Minggu → Velbak",
    stops: [
      "Pasar Minggu",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
    ],
  },
  {
    id: "6Q",
    number: "6Q",
    route_name: "Dukuh Atas - Casablanca via Epicentrum",
    direction: "Dukuh Atas → Casablanca",
    stops: [
      "Dukuh Atas",
      "Sudirman",
      "Setiabudi",
      "Kuningan",
      "Epicentrum",
      "Casablanca",
    ],
  },
  {
    id: "6T",
    number: "6T",
    route_name: "Pasar Minggu - Velbak via Kebon Jeruk",
    direction: "Pasar Minggu → Velbak",
    stops: [
      "Pasar Minggu",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
    ],
  },
  {
    id: "6U",
    number: "6U",
    route_name: "Blok M - Pasar Minggu",
    direction: "Blok M → Pasar Minggu",
    stops: [
      "Blok M",
      "Sudirman",
      "Bundaran HI",
      "Monumen Nasional",
      "Gambir 1",
      "Kwitang",
      "Atrium Senen",
      "Senen",
      "Tegalan",
      "Matraman",
      "Jatinegara",
      "Cipinang",
      "Pasar Rebo",
      "Kampung Rambutan",
      "Kampung Melayu",
      "Stasiun Manggarai",
      "Blok M",
    ],
  },
  {
    id: "6V",
    number: "6V",
    route_name: "Pasar Minggu - Velbak via Kebon Jeruk",
    direction: "Pasar Minggu → Velbak",
    stops: [
      "Pasar Minggu",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
    ],
  },
  {
    id: "6W",
    number: "6W",
    route_name: "Duren Tiga - Blok M via Bangka Raya",
    direction: "Duren Tiga → Blok M",
    stops: [
      "Duren Tiga",
      "Pasar Minggu",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Bangka Raya",
      "Blok M",
    ],
  },
  {
    id: "7",
    number: "7",
    route_name: "Ragunan - Kampung Rambutan",
    direction: "Ragunan → Kampung Rambutan",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Kemang",
      "Cilandak",
      "Pasar Minggu",
      "Kampung Rambutan",
    ],
  },
  {
    id: "7A",
    number: "7A",
    route_name: "Ragunan - Balai Kota via Kuningan",
    direction: "Ragunan → Balai Kota",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Underpass Kuningan",
      "Patra Kuningan",
      "Setiabudi Barat",
      "Setiabudi Tengah",
      "Dukuh Atas",
      "Sudirman",
      "Balai Kota",
    ],
  },
  {
    id: "7B",
    number: "7B",
    route_name: "Ragunan - Balai Kota via Semanggi",
    direction: "Ragunan → Balai Kota",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Semanggi",
      "Sudirman",
      "Balai Kota",
    ],
  },
  {
    id: "7C",
    number: "7C",
    route_name: "Stasiun Tebet - Kuningan",
    direction: "Stasiun Tebet → Kuningan",
    stops: [
      "Stasiun Tebet 2 - Pintu Barat",
      "Departemen Kesehatan",
      "Mampang Prapatan",
      "Karet",
      "Karet Sudirman",
      "Setiabudi Barat",
      "Setiabudi Tengah",
      "Kuningan",
    ],
  },
  {
    id: "7D",
    number: "7D",
    route_name: "Stasiun Tebet - Bundaran Senayan",
    direction: "Stasiun Tebet → Bundaran Senayan",
    stops: [
      "Stasiun Tebet 2 - Pintu Barat",
      "Departemen Kesehatan",
      "Mampang Prapatan",
      "Semanggi",
      "Sudirman",
      "Bundaran Senayan",
    ],
  },
  {
    id: "7E",
    number: "7E",
    route_name: "Ragunan - Blok M via Bangka Raya",
    direction: "Ragunan → Blok M",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Bangka Raya",
      "Blok M",
    ],
  },
  {
    id: "7F",
    number: "7F",
    route_name: "Blok M - Lebak Bulus",
    direction: "Blok M → Lebak Bulus",
    stops: [
      "Blok M",
      "Sudirman",
      "Bundaran HI",
      "Monumen Nasional",
      "Gambir 1",
      "Kwitang",
      "Atrium Senen",
      "Senen",
      "Tegalan",
      "Matraman",
      "Jatinegara",
      "Cipinang",
      "Pasar Rebo",
      "Kampung Rambutan",
      "Lebak Bulus",
    ],
  },
  {
    id: "7P",
    number: "7P",
    route_name: "Pasar Minggu - Velbak",
    direction: "Pasar Minggu → Velbak",
    stops: [
      "Pasar Minggu",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
    ],
  },
  {
    id: "7Q",
    number: "7Q",
    route_name: "Dukuh Atas - Casablanca",
    direction: "Dukuh Atas → Casablanca",
    stops: [
      "Dukuh Atas",
      "Sudirman",
      "Setiabudi",
      "Kuningan",
      "Epicentrum",
      "Casablanca",
    ],
  },
  {
    id: "7R",
    number: "7R",
    route_name: "Ragunan - Kuningan",
    direction: "Ragunan → Kuningan",
    stops: [
      "Ragunan",
      "Simpang Ragunan Ar-Raudhah",
      "Jati Barat",
      "Jati Padang",
      "Mampang Prapatan",
      "Underpass Kuningan",
      "Patra Kuningan",
      "Kuningan",
    ],
  },
  {
    id: "7T",
    number: "7T",
    route_name: "Pasar Minggu - Velbak via Kebon Jeruk",
    direction: "Pasar Minggu → Velbak",
    stops: [
      "Pasar Minggu",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
    ],
  },
  {
    id: "7U",
    number: "7U",
    route_name: "Blok M - Pasar Minggu",
    direction: "Blok M → Pasar Minggu",
    stops: [
      "Blok M",
      "Sudirman",
      "Bundaran HI",
      "Monumen Nasional",
      "Gambir 1",
      "Kwitang",
      "Atrium Senen",
      "Senen",
      "Tegalan",
      "Matraman",
      "Jatinegara",
      "Cipinang",
      "Pasar Rebo",
      "Kampung Rambutan",
      "Pasar Minggu",
    ],
  },
  {
    id: "7V",
    number: "7V",
    route_name: "Pasar Minggu - Velbak",
    direction: "Pasar Minggu → Velbak",
    stops: [
      "Pasar Minggu",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
    ],
  },
  {
    id: "7W",
    number: "7W",
    route_name: "Duren Tiga - Blok M via Bangka Raya",
    direction: "Duren Tiga → Blok M",
    stops: [
      "Duren Tiga",
      "Pasar Minggu",
      "Tebet",
      "Mampang Prapatan",
      "Warung Jati Barat",
      "Jati Padang",
      "Lebak Bulus",
      "Bangka Raya",
      "Blok M",
    ],
  },
  {
    id: "8",
    number: "8",
    route_name: "Lebak Bulus - Harmoni",
    direction: "Lebak Bulus → Harmoni",
    stops: [
      "Lebak Bulus",
      "Cipete Raya",
      "Fatmawati",
      "Panglima Polim",
      "Blok M",
      "Senayan JCC",
      "Gelora Bung Karno",
      "Karet Sudirman",
      "Bundaran HI",
      "Monas/Harmoni",
    ],
  },
  {
    id: "8A",
    number: "8A",
    route_name: "Lebak Bulus - Harmoni via Sudirman",
    direction: "Lebak Bulus → Harmoni",
    stops: [
      "Lebak Bulus",
      "Fatmawati",
      "Panglima Polim",
      "Blok M",
      "Sudirman",
      "Bundaran HI",
      "Monas/Harmoni",
    ],
  },
  {
    id: "8C",
    number: "8C",
    route_name: "Lebak Bulus - Senen",
    direction: "Lebak Bulus → Senen",
    stops: [
      "Lebak Bulus",
      "Fatmawati",
      "Cipete Raya",
      "Blok M",
      "Sudirman",
      "Bundaran HI",
      "Thamrin",
      "Senen",
    ],
  },
  {
    id: "8D",
    number: "8D",
    route_name: "Lebak Bulus - Kuningan",
    direction: "Lebak Bulus → Kuningan",
    stops: [
      "Lebak Bulus",
      "Cipete Raya",
      "Fatmawati",
      "Panglima Polim",
      "Blok M",
      "Sudirman",
      "Kuningan",
    ],
  },
  {
    id: "8E",
    number: "8E",
    route_name: "Lebak Bulus - Dukuh Atas",
    direction: "Lebak Bulus → Dukuh Atas",
    stops: [
      "Lebak Bulus",
      "Fatmawati",
      "Panglima Polim",
      "Blok M",
      "Sudirman",
      "Dukuh Atas",
    ],
  },
  {
    id: "8K",
    number: "8K",
    route_name: "Lebak Bulus - Karet",
    direction: "Lebak Bulus → Karet",
    stops: [
      "Lebak Bulus",
      "Cipete Raya",
      "Fatmawati",
      "Blok M",
      "Sudirman",
      "Karet",
    ],
  },
  {
    id: "8M",
    number: "8M",
    route_name: "Lebak Bulus - Blok M via Kemang",
    direction: "Lebak Bulus → Blok M",
    stops: [
      "Lebak Bulus",
      "Cipete Raya",
      "Fatmawati",
      "Panglima Polim",
      "Kemang",
      "Blok M",
    ],
  },
  {
    id: "8N",
    number: "8N",
    route_name: "Lebak Bulus - Blok M via Bangka Raya",
    direction: "Lebak Bulus → Blok M",
    stops: [
      "Lebak Bulus",
      "Cipete Raya",
      "Fatmawati",
      "Panglima Polim",
      "Bangka Raya",
      "Blok M",
    ],
  },
];

module.exports = brtRoutes;
